spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev		#开发环境
  applicaiton:
    name: microservicecloud-config-yanlinlung-dev
---
spring:
  profiles: test	#测试环境
  applicaiton:
    name: microservicecloud-config-yanlinlung-test